### PR TITLE
Combine features of QualityTask and QualityObserver

### PR DESCRIPTION
**Pull request by knopers8**
Some of the decisions I took (which we can always discuss):
    - I used the `qualityGroups` key to list all the input objects groups
    - The aggregated quality is treated like any other quality. To reproduce the previous behaviour one can put it first in the global list of input objects groups.
    - All input objects may have additional comments which depend on the quality, which allows to still get the old behaviour for the aggregated quality, but also for any other (which would be asked for anyway at some point, I believe).
    - the inputObjects list contain separate JSON objects with all the possible keys for easier extensibility of configuration while letting users skip some optional fields.
    - when a QO cannot be retrieved, we still print the corresponding line, so this fact is known
    - input object groups get both a title and a name. The name is used for paths in QCDB to corresponding trends and histograms
    - observeDetails and qualityDetailChoice was reduced to ignoreQualitiesDetails, since an empty list would be in fact equal to "observeDetails" : "true" with all qualities listed, so does not using this setting at all. The parameter is per group and an actual JSON list is used, to avoid errors in parsing.
    - timestamps are kept separate to configuration, since they are state, not configuration.

`qc/TST/MO/ExampleQualityTask` in qcg-test contains an example output.

### CODE REVIEW

**Comment by knopers8** [comment]
@aferrero2707 @mlesch could you please have a look?

**Comment by mlesch** [comment]
Hi @knopers8 

Thanks a lot for the update! I had a look at the PR gradually over the past couple of days, and to me it looks good in regards of the QualityObserver. I just have two questions: 

- Regarding your point " All input objects may have additional comments which depend on the quality, which allows to still get the old behavior for the aggregated quality, but also for any other (which would be asked for anyway at some point, I believe).": 
Is this set via the FlagReasons in the QO itself? So e.g. if I have a checker, I can add a comment for some specific qualities? I'm asking because I did not look yet in detail into the FlagReasons. In that sense, is it also possible that multiple comments are given? Currently for the TPC, we save in the metadata of the QO why it failed, and also some comments that can be set via the json file so that the shifter is informed if there is something important about a check. Is this still possible?
- I see in your example, that the aggregated quality and the single qualities of the group are separated by a dashed line. But the example itself is just one group. How are different groups separated? In the QualityObserver the groups themselves are separated by the dashed line. I'm just asking so that it becomes clear to the shifter what belongs to what

**Comment by knopers8** [comment]
> Regarding your point " All input objects may have additional comments which depend on the quality, which allows to still get the old behavior for the aggregated quality, but also for any other (which would be asked for anyway at some point, I believe).":
Is this set via the FlagReasons in the QO itself?

In this comment I meant adding a shifter-oriented message in the configuration, which is on the top of the comment in `FlagReason`. It's this:
```
              {
                "name" : "QcCheck",
                "title" : "Aggregated TST Quality",
                "messageBad" : "Inform XYZ on-call immediately",
                "messageMedium": "Add bookkeeping entry",
                "messageGood": "All checks are OK",
                "messageNull": "Some histograms are empty!!!"
              }
```
Regardless of that, you can add a comment to `FlagReason` in the check, as you suggested here:

> So e.g. if I have a checker, I can add a comment for some specific qualities? In that sense, is it also possible that multiple comments are given?

Here is an example of this: https://github.com/AliceO2Group/QualityControl/blob/master/Modules/Skeleton/src/SkeletonCheck.cxx#L57 
As you can see, you can add multiple `FlagReasons`, each having a different comment.

> Currently for the TPC, we save in the metadata of the QO why it failed, and also some comments that can be set via the json file so that the shifter is informed if there is something important about a check. Is this still possible?

Yes, so essentially you can add hardcoded comments in Check code and configurable ones on the top with this PR.

> I see in your example, that the aggregated quality and the single qualities of the group are separated by a dashed line. But the example itself is just one group.

I don't understand. Both the example in `postprocessing.json` and the one in documentation have two JSON objects in `qualityGroups`, which correspond to the two groups separated by the dashed line:
```
        "qualityGroups": [ 
          {                                        # THE FIRST GROUP BEGINS HERE
            "name" : "global",
            "title" : "GLOBAL TST QUALITY",
            "path": "TST/QO",
            "ignoreQualitiesDetails" : ["Null", "Good", "Medium", "Bad"],
            "inputObjects": [
              {
                "name" : "QcCheck",
                "title" : "Aggregated TST Quality",
                "messageBad" : "Inform XYZ on-call immediately",
                "messageMedium": "Add bookkeeping entry",
                "messageGood": "All checks are OK",
                "messageNull": "Some histograms are empty!!!"
              }
            ]
          },
          {            # THE SECOND GROUP BEGINS HERE
            "name" : "details",
            "title" : "TST DETAILS",
            "path": "TST/QO",
            "ignoreQualitiesDetails" : [],
            "inputObjects": [
              {
                "name" : "QcCheck",
                "title" : ""
              },
              {
                "name" : "someNumbersCheck",
                "title" : ""
              },
              {
                "name" : "XYZCheck",
                "title" : ""
              }
            ]
          }
        ],
```

**Comment by aferrero2707** [comment]
@knopers8 @mlesch merged, I will give it a try as soon as I manage, and report back. For me the general structure of the configuration looks ok, flexible enough to accomodate all the use cases I can currently think of.

**Pull request merged**
